### ISSUE TITLE
Allow aliasing commands instead of running lets inside lets

### ISSUE THREAD

**Issue by kindermax** [lets-cli/lets#120]
Consider this

```yaml
commands:
  run:
    depends: [build-img-1, build-img-2]
    cmd: echo Run

  build-img-1:
    cmd: lets _build-image first.Dockerfile


  build-img-2:
    cmd: lets _build-image second.Dockerfile


  _build-image:
    options: |
      Usage: lets _build-image <image>
    cmd: docker build . -f ${LETSOPT_IMAGE}
    
```

It would be more cool to not run lets-in-lets. Something like this

```yaml
commands:
  run:
    depends: [build-img-1, build-img-2]
    cmd: echo Run

  build-img-1:
    ref: _build_image 
    args: first.Dockerfile


  build-img-2:
    ref: _build_image 
    args: second.Dockerfile


  _build-image:
    options: |
      Usage: lets _build-image <image>
    cmd: docker build . -f ${LETSOPT_IMAGE}
```

This way we do not run lets in lets, we just say - reference _build_image and pass args first.Dockerfile

Maybe it makes sense to separate this new ref commands into `aliases` top level directive or smth like this
