### ISSUE TITLE
Implement parallel cmds execution

### ISSUE THREAD

**Issue by danylkaaa** [lets-cli/lets#17]
In some cases I need to run two or more jobs in parallel. For ex. compile TS code and serve it over HTTP. Now I need to open two or more terminal sessions and run cmds. It will be great if I will be able to write in `lets.yaml` like:
```yaml
commands:
   compile-ts:
      cmd: npm run build
   serve:
      cmd: npm run serve
   serve-compiled:
      cmds:
      - compile-ts
      - serve-compiled
```

Also It will be great, if lets will decorate each stdout of subproceses like docker-compose:
```bash
[compile-ts]: foo
[serve]: bar
```

**Comment by kindritskyiMax** [comment]
Good idea. Would you like to make a PR for this feature?

**Comment by kindermax** [comment]
Just adding yet another variant of implementation here. Later we have to decide, which one to use (or both, why not).

The idea is to allow `cmd` to be a map. Thus we will have named commands and it will make possible to include or exclude some of the commands:

`lets run --exclude nginx`
`lets run --only nginx`

```yaml
run:
  cmd:
     all: docker-compose up uaprom-dev redis
     nginx: docker-compose up nginx
```
This will run all commands - nginx in paralel - and now we can controll nginx separately - disable logs, do not run at all
