### ISSUE TITLE
Allow env propagation to commands declared in depends

### ISSUE THREAD

**Issue by kindermax** [lets-cli/lets#19]
Something like this. Syntax is discussable

```sh
commands:
  foo:
    env:
       MYENV: "1"
     depends: [bar]
  bar:
    cmd: echo ${MYENV}
```

**Comment by kindermax** [comment]
Another solution is to extend depends syntax to have maps as values in depends array 

```yaml
commands:
  foo:
    env:
       MYENV: "1"
     depends:
       - task: bar
         env:
           MYENV: "2"
         parent_env: true

  bar:
    cmd: echo ${MYENV}
```

`parent_env: true` means we want to pass parent env to dependency.

So either by overriding env or passing parent env we can change deps env.
