### ISSUE TITLE
usage question: cannot export .env variables using lets

### ISSUE THREAD

**Issue by bgalvao** [lets-cli/lets#191]
This is probably not an issue with lets-cli, just something I've looked up on stack overflow and cannot get it to work.

I want to export variables in a docker swarm project:

```yaml
load-env:
    description: Loads environment variables specified in stacks/swarm.env into the current shell.
    cmd: set -a; . stacks/swarm.env; set +a
```

Running `set -a; . stacks/swarm.env; set +a` exports the variables in the env file, but running `lets load-env` does not. I haven't been able to figure out why.

I also tried `export $(cat stacks/swarm.env) > /dev/null 2>&1;` and it works the same way.
