### ISSUE TITLE
Deduplicate depends

### ISSUE THREAD

**Issue by kindermax** [lets-cli/lets#261]
Problem:

If commands have duplicate nested depends we will execute them all, for example:

```yaml
commands:
  build-image: docker build -f Dockerfile .
  build-all:
    depends: [build-image]

  run:
    depends: [build-image, build-all]
   cmd: npm run dev
```

In the example above we will run `build-image` twice - once `run:build_image` and second `run:build-all:build-image`

Solution:

We can try to duplicate depends on config parse step since we know want command chain will be executed.
