### ISSUE TITLE
Add ability to skip tasks,if checksum for this traks was not changed

### ISSUE THREAD

**Issue by danylkaaa** [lets-cli/lets#32]
Sometimes I want to skip execution of some tasks, if command's checksum from last run is not changed. 
Example: before each `npm run smth` I want to run `npm i`. But if `package.json` and `package.lock` is not changed, I do not need to run `npm i`

So, in `lets.yaml` I want to past smth like this and as a result, omit running task

New lets.yaml 
```yaml
install_deps:
  checksum:
    deps: &deps
      - package.json    
      - package-lock.json
  only:
    checksum:
      <<: *deps
  cmd: npm i

run-smth:
  depends: [install_deps]
  cmd: npm run smth
```

As you can see, in `lets.yaml` I added in cmd `install_deps` property `only`. It will allow to execute `install_deps.cmd` only if checksum for this cmd changed. 

So, what we need to implement:
- Persistant saving of checksums into file
- Reading saved checksum for command
- Updating of after cmd successful execution
- Skip command invocation, if new and saved checksum are equal
