### ISSUE TITLE
Implement some sort of a clean or on_stop directive

### ISSUE THREAD

**Issue by kindermax** [lets-cli/lets#34]
It may be useful to declare cleanup command.

Example:

```yaml
commands:
  run: 
   cmd: |
     docker-compose up some-service -d
     npm run app
   on_stop:
     docker-compose down
```

I will allow to explicitly declare what to do when a command stopped either by error or Ctrl+c

**Comment by danylkaaa** [comment]
Maybe it will be more clear, if you've name this property `after`?

**Comment by kindermax** [comment]
Another option is to allow `cmd` be a list of strings:

```yaml
foo:
  cmd: echo Foo

bar:
  cmd:
   - echo B
   - echo A
   - echo R
```
