### ISSUE TITLE
add bats tests for positional args

### ISSUE THREAD

**Issue by kindermax** [lets-cli/lets#50]
test how to use positional args appending

```yaml
commands:
  build-js:
    cmd:
      - npm 
      - run 
      - webpack
```

```bash
lets build-js --watch
```
