### ISSUE TITLE
add group field for a better command list formatting

### ISSUE THREAD

**Issue by kindermax** [lets-cli/lets#60]
```yaml
commands:
  lint:
    group: codequality
    cmd: eslint
  test:
    group: tests
    cmd: jest
```

and the output will be grouped and indented

```
Available commands:
  [codequality]
    lint
  [tests]
    test
```
