### ISSUE TITLE
eval_env in command hangs when executing lets

### ISSUE THREAD

**Issue by kindermax** [lets-cli/lets#89]
```yaml
commands:
  js-dev:
    description: Build  js dev version
    eval_env:
      CHECKSUM: echo `lets checksum`
    cmd: |
      docker build . -f Dockerfile --build-arg CHECKSUM=${CHECKSUM}
```
